import Head from 'next/head'
import Banner from '../components/banner/banner'
import SectionCards from '../components/card/section-cards'
import NavBar from '../components/nav/navbar'
import { getPopularVideos, getVideos, getWatchItAgainVideos } from '../lib/videos'
import styles from '../styles/Home.module.css'
import { redirectUser } from '../utils/redirectUser'

export async function getServerSideProps(context) {

  const { userId, token } = await redirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false
      }
    }
  }

  const disneyVideos = await getVideos("disney trailers");
  
  const productivityVideos = await getVideos("productivity");
  
  const travelVideos = await getVideos("travel");

  const popularVideos = await getPopularVideos();

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  return { props: { disneyVideos, productivityVideos, travelVideos, popularVideos, watchItAgainVideos }}

}

export default function Home({ disneyVideos, productivityVideos, travelVideos, popularVideos, watchItAgainVideos }) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <Banner
          videoId="4zH5iYM4wJo" 
          title="Clifford the Red Dog"
          subTitle="Thrilling Comedy"
          imgUrl="/static/clifford.webp"
        />
        <div className={styles.sectionWrapper}>
            <SectionCards title={"Disney"} videos={disneyVideos} size="large" />
            <SectionCards title={"Watch It Again"} videos={watchItAgainVideos} size="small" />
            <SectionCards title={"Travel"} videos={travelVideos} size="small" />
            <SectionCards title={"Productivity"} videos={productivityVideos} size="medium" />
            <SectionCards title={"Popular"} videos={popularVideos} size="small" />
        </div>
      </main>
    </div>
  )
}
